### ISSUE TITLE
Компонент "Блокировка скрола": скорректировать ссылку для скачивания zip файла

### ISSUE THREAD

**Issue by SchumovaMaria** [htmlonelove/liga-reshare#11]
Сейчас при скачивании файлов компонента "Блокировка скрола" (http://htmlonelove.top/liga-reshare/scroll-lock.html) загружается focus-lock.zip, а должен загружаться, скорее всего, scroll-lock.zip.

**Comment by redsmoke19** [comment]
Спасибо, исправили)
